server:
  port: 9080

logging:
  level:
    root: info

currency:
  rate:
    fetch:
      cron: 0 4 * * * *

cbr:
  url: https://www.cbr-xml-daily.ru/daily_json.js

retryable:
  maxAttempts: 2
  backoff:
    delay: 2000